CREATE TABLE [dbo].[Events]
(
  [EventId] INT NOT NULL PRIMARY KEY IDENTITY,
  [Title] NVARCHAR(100) NOT NULL,
	[Location] NVARCHAR(100) NOT NULL,
  [EventDate] DATETIME DEFAULT(GETDATE()) NOT NULL,
  [Text] NVARCHAR(4000) NOT NULL,
	[Going] INT DEFAULT((0)) NULL,
	[PdfFileType] VARCHAR(100) NULL,
	[PdfFileName] VARCHAR(100) NULL,
)
